import {createClient} from 'file:///E:/Genlayer-Tools/studio-next-toolchain/node_modules/genlayer-js/dist/index.js';
import {studioDevnet} from 'file:///E:/Genlayer-Tools/studio-next-toolchain/node_modules/genlayer-js/dist/chains/index.js';
import {readFileSync,writeFileSync} from 'node:fs';
const phase=process.argv[2]||'revision4';
if(!/^[a-z0-9-]+$/.test(phase))throw Error('Invalid phase');
const client=createClient({chain:studioDevnet});
const request={account:{address:'0x8170e7b22000527d9bab38dffa76b52103441b57'},address:'0x1eBE1f41ff016b74af41b94F5E07B3B3b29A4DEF',transactionHashVariant:'latest-final'};
const a=await client.readContract({...request,functionName:'get_assessment',args:['a'.repeat(64)]});
const b=await client.readContract({...request,functionName:'get_assessment',args:['b'.repeat(64)]});
const c=await client.readContract({...request,functionName:'get_assessment',args:['c'.repeat(64)]});
const e=await client.readContract({...request,functionName:'get_assessment',args:['e'.repeat(64)]});
const f=await client.readContract({...request,functionName:'get_assessment',args:['f'.repeat(64)]});
const unknownOracle=await client.readContract({...request,functionName:'is_deadline_resolved',args:['f'.repeat(64)]});
const lineage=await client.readContract({...request,functionName:'get_lineage',args:[]});
const aOriginal=JSON.parse(readFileSync(new URL('./tx-0xda0866be8441281c440da67461ee253903d98362ff9134e1306e7a4fdf2bedf6-reconciliation.json',import.meta.url))).assessment;
const bOriginal=JSON.parse(readFileSync(new URL('./tx-0x094230874cbc8ef078c8c20cb8ce9a68ea6209cb2f546f33d334e4ca7db6cf2f-reconciliation.json',import.meta.url))).assessment;
const checks={historicalAUnchanged:a===aOriginal,historicalBUnchanged:b===bOriginal,failedDriftAbsent:c==='',failedPdfAbsent:e==='',unknownEmpty:f==='',unknownOracleFalse:unknownOracle===false,counterexampleExcluded:JSON.parse(a).controlling_deadline==='2026-06-30'&&JSON.parse(a).controlling_deadline!=='2027-12-21'};
const report={phase,network:'studio-dev',chainId:61997,address:request.address,blockTag:'latest-final',lineage,assessments:{a,b,c,e,f},unknownOracle,checks,pass:Object.values(checks).every(Boolean)};
writeFileSync(new URL('./history-'+phase+'.json',import.meta.url),JSON.stringify(report,null,2));
console.log(JSON.stringify({phase,checks,pass:report.pass,lineage}));
